language: php
php:
    - "7.2"
    - "7.1"
    - "7.0"
    - "5.6"
    - "5.5"
    - "5.4"

env:
    - CONTAO_VERSION=~2.11.0
    - CONTAO_VERSION=~3.1.0
    - CONTAO_VERSION=~3.2.0
    - CONTAO_VERSION=~3.3.0

install:
    - composer require contao/core $CONTAO_VERSION --prefer-dist --dev
    - composer install --prefer-dist --dev

script: ant -keep-going
